{{- if .Values.service.create -}}
apiVersion: v1
kind: Service
metadata:
  {{- if ne .Values.service.name "" }}
  name: "{{ .Values.service.name }}"
  {{- else }}
  name: "{{ .Values.applicationName }}"
  {{- end }}
  namespace: {{ .Values.serviceNamespace }}
  labels:
    whitbread.services/name: {{ .Values.applicationName }}
    app: {{ .Values.applicationName }}
    {{- with .Values.service.labels }}
    {{ toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- toYaml .Values.service.annotations | trim | nindent 4 }} 
spec:
  type: {{ .Values.service.type }}
  {{- with .Values.service.ports }}
  ports:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  selector:
    app: {{ .Values.applicationName }}
    whitbread.services/name: {{ .Values.applicationName }}
{{- end -}}